#!/bin/sh
### BEGIN INIT INFO
# Provides:          rpi-surveillance
# Required-Start:    $syslog
# Required-Stop:     $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start RPi Surveillance server at boot time
# Description:       Enable service provided by daemon.
### END INIT INFO

RPI_SURVEILLANCE_PATH=/home/pi/RaspiSecurity
RPI_SURVEILLANCE_PIDFILE=/var/run/rpi-surveillance.pid
RPI_SURVEILLANCE_NAME=`basename $0`

case "$1" in
    start)
        echo "Starting $RPI_SURVEILLANCE_NAME"
        cd $RPI_SURVEILLANCE_PATH && python server.py & echo $! > $RPI_SURVEILLANCE_PIDFILE
        ;;
    stop)
        echo "Stopping $RPI_SURVEILLANCE_NAME"
        if [ -f $RPI_SURVEILLANCE_PIDFILE ]; then
            kill $(cat $RPI_SURVEILLANCE_PIDFILE)
            rm $RPI_SURVEILLANCE_PIDFILE
        fi
        ;;
    restart)
        # Hacky way to restart
        status=`curl -s http://localhost:5555/status`
        ./$0 stop
        ./$0 start
        if [ "$status" = Running ]; then
            sleep 2
            curl -s http://localhost:5555/start > /dev/null
            exit $?
        fi
        ;;
    start-camera)
        echo "Starting $RPI_SURVEILLANCE_NAME camera"
        curl -s http://localhost:5555/start > /dev/null
        ;;
    stop-camera)
        echo "Stopping $RPI_SURVEILLANCE_NAME camera"
        curl -s http://localhost:5555/stop > /dev/null
        ;;
    status)
        if [ -f $RPI_SURVEILLANCE_PIDFILE ]; then
            status=`curl -s http://localhost:5555/status`
            echo "Server running; camera $status"
        else
            echo "Server stopped"
            exit 1
        fi
        ;;
    *)
        echo "Usage: $0 {start|stop|restart|start-camera|stop-camera|status}"
        exit 1
        ;;
esac

exit 0
